#!/usr/bin/env python3
"""Generate appendix_circuits.tex from the circuit JSON artifacts.

Emits one appendix section per circuit: the full gate listing (signal
assignments), the output-signal map, and the canonical SHA-256, all read
directly from circuits/*.json and bounds.json so the PDF listing cannot
drift from the machine-checkable artifacts.
"""

from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
ORDER = [
    "mixcolumns_97gates_depth3",
    "mixcolumns_92gates_depth4",
    "mixcolumns_89gates_depth5",
    "mixcolumns_88gates_depth7",
    "mixcolumns_88gates_depth8",
]

# Extra text for the section heading, and a status note printed under it.
HEADING_SUFFIX = {
    "mixcolumns_88gates_depth7": "; ties the published floor",
    "mixcolumns_88gates_depth8": "; derived, non-frontier",
}
STATUS_NOTE = {
    "mixcolumns_88gates_depth7": (
        r"\emph{Status: the same (depth, count) point as Jean~\cite{Jean26}, reached "
        r"independently on this project's own lineage; 61 of 88 internal masks are shared. "
        r"It ties that point and does not beat it, and Jean has priority.}"
    ),
    "mixcolumns_88gates_depth8": (
        r"\emph{Status: derived from published work, and not a frontier point. Its seed chain "
        r"passes through Jean's published 88-gate circuit~\cite{Jean26} (Section~\ref{sec:results}), "
        r"and it is dominated by Appendix~\ref{app:mixcolumns_88gates_depth7} (same count, greater "
        r"depth). It is listed as a verified distinct construction, not as a claim.}"
    ),
}


def tex_escape(s: str) -> str:
    return s.replace("_", r"\_")


def main() -> None:
    bounds = {
        e["id"]: e
        for e in json.loads((ROOT / "bounds.json").read_text(encoding="utf-8"))["circuits"]
    }
    out = []
    out.append("% Auto-generated by paper/generate_appendix.py -- do not edit by hand.")
    for cid in ORDER:
        data = json.loads((ROOT / "circuits" / f"{cid}.json").read_text(encoding="utf-8"))
        gates = data["gates"]
        outs = data["outputSignals"]
        b = bounds[cid]
        suffix = HEADING_SUFFIX.get(cid, "")
        out.append(rf"\section{{Circuit \texttt{{{tex_escape(cid)}}} ({data['gateCount']} gates, depth {data['depth']}{suffix})}}")
        out.append(rf"\label{{app:{cid}}}")
        if cid in STATUS_NOTE:
            out.append(r"\noindent " + STATUS_NOTE[cid] + r"\\[3pt]")
        out.append(
            r"Signals $s_0,\dots,s_{31}$ are the inputs; gate $k$ produces "
            rf"$s_{{32+k}}$. Canonical gate-list SHA-256 (see Section~\ref{{sec:verification}}): \\"
        )
        out.append(rf"\texttt{{\small {b['sha256_canonical_gates']}}}")
        out.append(r"\begin{multicols}{4}\scriptsize\ttfamily")
        lines = []
        for k, (a, bb) in enumerate(gates):
            lines.append(rf"s{32 + k} = s{a} $\oplus$ s{bb} \\")
        out.append("\n".join(lines))
        out.append(r"\end{multicols}")
        out.append(r"\noindent Output signals (output bit $j$ is carried by the listed signal, $j = 0,\dots,31$):")
        out.append(r"\begin{center}\scriptsize\ttfamily")
        row = ", ".join(str(x) for x in outs)
        out.append(rf"[{row}]")
        out.append(r"\end{center}")
        out.append("")
    (ROOT / "paper" / "appendix_circuits.tex").write_text("\n".join(out) + "\n", encoding="utf-8")
    print(f"wrote appendix_circuits.tex ({sum(1 for _ in ORDER)} circuits)")


if __name__ == "__main__":
    main()
