#!/usr/bin/env python3
"""Generate appendix_circuits.tex from the circuit JSON artifacts.

Emits one appendix section per circuit: the full gate listing (signal
assignments), the output-signal map, and the canonical SHA-256, all read
directly from circuits/*.json and bounds.json so the PDF listing cannot
drift from the machine-checkable artifacts.
"""

from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
ORDER = [
    "mixcolumns_89gates",
    "mixcolumns_98gates_depth3",
    "mixcolumns_91gates_depth6",
]


def tex_escape(s: str) -> str:
    return s.replace("_", r"\_")


def main() -> None:
    bounds = {
        e["id"]: e
        for e in json.loads((ROOT / "bounds.json").read_text(encoding="utf-8"))["circuits"]
    }
    out = []
    out.append("% Auto-generated by paper/generate_appendix.py -- do not edit by hand.")
    for letter, cid in zip("ABC", ORDER):
        data = json.loads((ROOT / "circuits" / f"{cid}.json").read_text(encoding="utf-8"))
        gates = data["gates"]
        outs = data["outputSignals"]
        b = bounds[cid]
        out.append(rf"\section{{Circuit \texttt{{{tex_escape(cid)}}} ({data['gateCount']} gates, depth {data['depth']})}}")
        out.append(rf"\label{{app:{cid}}}")
        out.append(
            r"Signals $s_0,\dots,s_{31}$ are the inputs; gate $k$ produces "
            rf"$s_{{32+k}}$. Canonical gate-list SHA-256 (see Section~\ref{{sec:verification}}): \\"
        )
        out.append(rf"\texttt{{\small {b['sha256_canonical_gates']}}}")
        out.append(r"\begin{multicols}{3}\scriptsize\ttfamily")
        lines = []
        for k, (a, bb) in enumerate(gates):
            lines.append(rf"s{32 + k} = s{a} $\oplus$ s{bb} \\")
        out.append("\n".join(lines))
        out.append(r"\end{multicols}")
        out.append(r"\noindent Output signals (output bit $j$ is carried by the listed signal, $j = 0,\dots,31$):")
        out.append(r"\begin{center}\scriptsize\ttfamily")
        row = ", ".join(str(x) for x in outs)
        out.append(rf"[{row}]")
        out.append(r"\end{center}")
        out.append("")
    (ROOT / "paper" / "appendix_circuits.tex").write_text("\n".join(out) + "\n", encoding="utf-8")
    print(f"wrote appendix_circuits.tex ({sum(1 for _ in ORDER)} circuits)")


if __name__ == "__main__":
    main()
